[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration",
]

[tool.flake8]
exclude = [
    ".venv",
    "build"
]
max-line-length = 119
# entend-ignore = "W293"
