name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run tests
        run:  pytest -vv --junitxml=test-result.xml
      - name: publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-result.xml
          check_name: Test Result Dundier Rewards (Pyhon ${{matrix.python-version}})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_retries: 10
          comment_mode: always
          fail_on: test failures
          time_unit: seconds
          ignore_runs: false
          hide_comments: all but latest
          job_summary: true
          compare_to_earlier_commit: true
          pull_request_build: merge
          check_run_annotations: all tests, skipped tests
          seconds_between_github_reads: 0.25
          seconds_between_github_writes: 2.0
          json_thousands_separator:  


permissions:
  checks: write
  contents: read
  pull-requests: write
